version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "secret"
      DATABASE_URL: "postgresql://supernote:postgres@database:5432/supernote?schema=public"
  database:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: supernote
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supernote
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: